# Generated by Django 3.2.8 on 2021-10-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=30)),
                ('email', models.EmailField(default=0, max_length=60)),
                ('phone_number', models.IntegerField(default=0)),
                ('location', models.CharField(default='no location', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=30)),
                ('email', models.EmailField(default=0, max_length=60)),
                ('phone_number', models.IntegerField(default=0)),
                ('location', models.CharField(default='no location', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no status', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='no data', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(default='no data', max_length=255)),
                ('donor', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcaresupplies.donor')),
                ('hospital', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthcaresupplies.hospital')),
                ('order_status', models.ForeignKey(default='no status', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthcaresupplies.status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('location', models.CharField(default='no location', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
